import { Link } from "@tanstack/react-router";
import { ArrowRight, MessageCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { whatsappUrl } from "@/lib/site-data";

export function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="eyebrow">{children}</p>; }
export function PageHero({ eyebrow, title, intro }: { eyebrow: string; title: string; intro: string }) { return <section className="page-hero"><div className="site-container"><Eyebrow>{eyebrow}</Eyebrow><h1 className="page-title">{title}</h1><p className="page-intro">{intro}</p></div></section>; }
export function Breadcrumbs({ current, parent, parentTo }: { current: string; parent?: string; parentTo?: string }) { return <nav aria-label="Caminho" className="breadcrumbs"><Link to="/">Início</Link><span>/</span>{parent && parentTo ? <><Link to={parentTo}>{parent}</Link><span>/</span></> : null}<span aria-current="page">{current}</span></nav>; }
export function ArrowLink({ to, children }: { to: string; children: React.ReactNode }) { return <Link to={to} className="arrow-link">{children}<ArrowRight /></Link>; }
export function FinalCta({ title = "Seu cuidado pode começar com uma conversa.", text = "Conte-nos o que você está buscando. Vamos entender juntos o melhor caminho para o seu caso." }: { title?: string; text?: string }) { return <section className="cta-band"><div className="site-container grid items-end gap-8 md:grid-cols-[1fr_auto]"><div><Eyebrow>Próximo passo</Eyebrow><h2 className="section-title max-w-3xl text-cream">{title}</h2><p className="mt-5 max-w-2xl text-cream/70">{text}</p></div><div className="flex flex-wrap gap-3"><Button asChild variant="gold" size="lg"><a href={whatsappUrl()} target="_blank" rel="noreferrer">Agendar avaliação</a></Button><Button asChild variant="outlineDark" size="lg"><a href={whatsappUrl("Olá! Gostaria de conversar com a equipe da Lacort.")} target="_blank" rel="noreferrer"><MessageCircle />WhatsApp</a></Button></div></div></section>; }