/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtigosCientificosRouteImport } from './routes/artigos-cientificos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as PacientesRouteImport } from './routes/pacientes'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as TratamentosRouteImport } from './routes/tratamentos'
import { Route as TratamentosSlugRouteImport } from './routes/tratamentos/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigosCientificosRoute = ArtigosCientificosRouteImport.update({
  id: '/artigos-cientificos',
  path: '/artigos-cientificos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesRoute = PacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const TratamentosRoute = TratamentosRouteImport.update({
  id: '/tratamentos',
  path: '/tratamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const TratamentosSlugRoute = TratamentosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TratamentosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artigos-cientificos': typeof ArtigosCientificosRoute
  '/contato': typeof ContatoRoute
  '/noticias': typeof NoticiasRoute
  '/pacientes': typeof PacientesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/tratamentos': typeof TratamentosRouteWithChildren
  '/tratamentos/$slug': typeof TratamentosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artigos-cientificos': typeof ArtigosCientificosRoute
  '/contato': typeof ContatoRoute
  '/noticias': typeof NoticiasRoute
  '/pacientes': typeof PacientesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/tratamentos': typeof TratamentosRouteWithChildren
  '/tratamentos/$slug': typeof TratamentosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artigos-cientificos': typeof ArtigosCientificosRoute
  '/contato': typeof ContatoRoute
  '/noticias': typeof NoticiasRoute
  '/pacientes': typeof PacientesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/tratamentos': typeof TratamentosRouteWithChildren
  '/tratamentos/$slug': typeof TratamentosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artigos-cientificos'
    | '/contato'
    | '/noticias'
    | '/pacientes'
    | '/politica-de-privacidade'
    | '/sobre'
    | '/termos-de-uso'
    | '/tratamentos'
    | '/tratamentos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artigos-cientificos'
    | '/contato'
    | '/noticias'
    | '/pacientes'
    | '/politica-de-privacidade'
    | '/sobre'
    | '/termos-de-uso'
    | '/tratamentos'
    | '/tratamentos/$slug'
  id:
    | '__root__'
    | '/'
    | '/artigos-cientificos'
    | '/contato'
    | '/noticias'
    | '/pacientes'
    | '/politica-de-privacidade'
    | '/sobre'
    | '/termos-de-uso'
    | '/tratamentos'
    | '/tratamentos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtigosCientificosRoute: typeof ArtigosCientificosRoute
  ContatoRoute: typeof ContatoRoute
  NoticiasRoute: typeof NoticiasRoute
  PacientesRoute: typeof PacientesRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  SobreRoute: typeof SobreRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  TratamentosRoute: typeof TratamentosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigos-cientificos': {
      id: '/artigos-cientificos'
      path: '/artigos-cientificos'
      fullPath: '/artigos-cientificos'
      preLoaderRoute: typeof ArtigosCientificosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes': {
      id: '/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof PacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tratamentos': {
      id: '/tratamentos'
      path: '/tratamentos'
      fullPath: '/tratamentos'
      preLoaderRoute: typeof TratamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tratamentos/$slug': {
      id: '/tratamentos/$slug'
      path: '/$slug'
      fullPath: '/tratamentos/$slug'
      preLoaderRoute: typeof TratamentosSlugRouteImport
      parentRoute: typeof TratamentosRoute
    }
  }
}

interface TratamentosRouteChildren {
  TratamentosSlugRoute: typeof TratamentosSlugRoute
}

const TratamentosRouteChildren: TratamentosRouteChildren = {
  TratamentosSlugRoute: TratamentosSlugRoute,
}

const TratamentosRouteWithChildren = TratamentosRoute._addFileChildren(
  TratamentosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtigosCientificosRoute: ArtigosCientificosRoute,
  ContatoRoute: ContatoRoute,
  NoticiasRoute: NoticiasRoute,
  PacientesRoute: PacientesRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  SobreRoute: SobreRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  TratamentosRoute: TratamentosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
